project:
  output-dir: results

execute:
  freeze: auto


render:
  - R/01_load.qmd
  - R/02_clean.qmd
  - R/03_augment.qmd
  - R/04_describe.qmd
  - R/05_analysis1.qmd
  - R/06_analysis2.qmd
  - R/00_all.qmd
